# Generated by Django 2.2.7 on 2019-11-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_options',
            new_name='product_options',
        ),
    ]
