# Generated by Django 2.2.7 on 2019-11-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20191125_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
