ports:
  - port: 8000
  - port: 3000
tasks:
  - command: >
          pypenv global 3.7.4 &&
          pipenv install django==2.2.7 &&
          pipenv install djangorestframework==3.10.3 &&
          pipenv install &&
          pipenv shell